AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Cloud Resume Challenge - Karam S

  Sample SAM Template 


Globals:
  Api:
    Cors:
      AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
  Function:
    Timeout: 3

Resources:
  VisitorCountFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: 's3://lambdaks/lambda_function.zip'
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::120697988561:role/VisitorCountRole
      Events:
        VisitorCount:
          Type: Api 
          Properties:
            Path: /visitor_count
            Method: get
            

Outputs:
  VisitorCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Visitor Count function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitor_count/"
  VisitorCountFunction:
    Description: "Visitor Count Lambda Function ARN"
    Value: !GetAtt VisitorCountFunction.Arn
  